/* Hallmark · pre-emit critique: P5 H5 E4 S5 R4 V5 */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CheckCircle2, Clock3, RefreshCw, ScanLine } from "lucide-react";
import toast from "react-hot-toast";
import axiosClient from "../../apis/axiosClient";
import ManageSidebar from "../../components/ManageSidebar";
import { translateError } from "../../utils/translateResponse";
import "./StaffDashboardPage.scss";

const dataOf = (response) => response?.data?.data || response?.data || {};
const StaffDashboardPage = () => { const [tickets, setTickets] = useState([]); const [loading, setLoading] = useState(true);
  const load = async () => { const id = "staff-dashboard-loading"; toast.loading("Đang tải ca vận hành...", { id }); setLoading(true); try { const response = await axiosClient.get("/tickets", { params: { page: 1, pageSize: 100 } }); setTickets(dataOf(response).tickets || []); toast.success("Đã cập nhật dữ liệu ca trực.", { id }); } catch (error) { toast.error(translateError(error), { id }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const checked = tickets.filter((ticket) => ticket.ticketStatus === "Checked"); const today = new Date().getDate(); const todayTickets = tickets.filter((ticket) => Number(ticket.ticketTypeId?.ticketTypeDate) === today); const max = Math.max(...[27, 28, 29].map((d) => tickets.filter((t) => Number(t.ticketTypeId?.ticketTypeDate) === d).length), 1); const hours = useMemo(() => ["08:00", "10:00", "12:00", "14:00", "16:00"].map((hour) => ({ hour, count: checked.filter((ticket) => new Date(ticket.checkedInAt).getHours() === Number(hour.slice(0, 2))).length })), [checked]);
  return <div className="dashboard-shell staff-dashboard"><ManageSidebar role="staff" activeItem="dashboard" /><main className="dashboard-main"><header className="dashboard-hero"><div><p className="dashboard-kicker">Trực cổng · hôm nay</p><h1>Nhịp check-in</h1><p>Tập trung vào những gì cần xử lý trong ca của bạn.</p></div><button className="dashboard-refresh" onClick={load} disabled={loading}><RefreshCw size={16} /> Làm mới</button></header><section className="dashboard-metrics"><Metric icon={<CheckCircle2 />} label="Đã check-in" value={checked.length || "—"} note="Tất cả ca trực" /><Metric icon={<ScanLine />} label="Vé trong ngày" value={todayTickets.length || "—"} note={`Ngày ${today}`} /><Metric icon={<Clock3 />} label="Lượt gần nhất" value={checked[0] ? new Date(checked[0].checkedInAt).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" }) : "—"} note="Theo thời gian server" /></section><section className="dashboard-grid"><ChartCard title="Vé theo ngày sự kiện" eyebrow="CỘT · QUÉT NHANH"><div className="bar-chart">{[27, 28, 29].map((day) => { const count = tickets.filter((t) => Number(t.ticketTypeId?.ticketTypeDate) === day).length; return <div className="bar-item" key={day}><strong>{count || "—"}</strong><div className="bar-track"><i style={{ height: `${Math.max((count / max) * 100, count ? 12 : 3)}%` }} /></div><span>Ngày {day}</span></div>; })}</div></ChartCard><ChartCard title="Check-in theo khung giờ" eyebrow="ĐƯỜNG · NHỊP CA TRỰC"><div className="line-chart"><div className="line-values">{hours.map((item) => <span key={item.hour}><b>{item.count || "—"}</b><em>{item.hour}</em></span>)}</div><svg viewBox="0 0 600 150"><path d="M25 110 C130 105 175 65 300 95 S430 35 575 50" /><circle cx="25" cy="110" r="5" /><circle cx="300" cy="95" r="5" /><circle cx="575" cy="50" r="5" /></svg></div></ChartCard></section><section className="dashboard-wide"><ChartCard title="Trạng thái vé" eyebrow="PIE · TÌNH HÌNH TẠI CỔNG"><div className="pie-layout"><div className="pie-chart" style={{ "--pie-progress": `${tickets.length ? Math.round((checked.length / tickets.length) * 100) : 0}%` }}><strong>{tickets.length ? `${Math.round((checked.length / tickets.length) * 100)}%` : "—"}</strong></div><div className="legend"><span><i className="legend-dot legend-dot--red" />Đã dùng <b>{checked.length}</b></span><span><i className="legend-dot legend-dot--gray" />Chờ check-in <b>{Math.max(tickets.length - checked.length, 0)}</b></span></div></div></ChartCard></section></main></div>; };
const Metric = ({ icon, label, value, note }) => <article className="metric-card"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;
const ChartCard = ({ title, eyebrow, children }) => <article className="chart-card"><header><div><p>{eyebrow}</p><h2>{title}</h2></div><ArrowUpRight size={18} /></header>{children}</article>;
export default StaffDashboardPage;
